### ISSUE TITLE
Cannot build. Internal compiler error

### ISSUE THREAD

**Issue by Cutta** [gejiaheng/Protein#5] opened 2017-06-16 13:55 UTC
It gets this error:
Error:16:49:27.066: SEVERE: com.android.jack.CommandLine: Internal compiler error (version 1.3-b19 'Douarn' (425700 24821ef75db0755f4803d46bd8bf9f37907c64ac by android-jack-team@google.com)):

**Comment by gejiaheng** [comment] 2017-06-16 14:52
Seems strange. The project doesn't enable jack compiler. Anyone else came across this error?

**Comment by gokulkrizh** [comment] 2017-06-17 05:32
@gejiaheng Error:Jack is required to support java 8 language features. Either enable Jack or remove sourceCompatibility JavaVersion.VERSION_1_8. 
when i enable jack it gives 
SEVERE: com.android.jack.CommandLine: Internal compiler error (version 1.3-b19 'Douarn' (425700 24821ef75db0755f4803d46bd8bf9f37907c64ac by android-jack-team@google.com)):

**Comment by gejiaheng** [comment] 2017-06-17 07:46
@gokrish6670 
You don't need to enable jack because jack is deprecated (https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html). And if you want to use Java 8, see https://developer.android.com/studio/preview/features/java8-support.html.   

As for your build error, what's your Android Studio and Java's version?

**Comment by gokulkrizh** [comment] 2017-06-17 11:16
@gejiaheng  used old gradle version.... updated to gradle version 3.0.0-alpha1, now it showing
Error:All flavors must now belong to a named flavor dimension. The flavor 'play' is not assigned to a flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html

**Comment by gejiaheng** [comment] 2017-06-18 13:00
@gokrish6670 
I don't think the android gradle plugin is too old. It works for me. 
Maybe it's your Android Studio? I'm using Android Studio 3.0 Canary 4. And use gradle wrapper instead of local gradle.

**Comment by Xiongxiangwei** [comment] 2017-06-19 10:52
I also have the same problem as the first floor, which doesn't seem to be compiled

**Comment by gejiaheng** [comment] 2017-06-20 02:20
I'll give you an example what my local environment is like:  

System: macOS
Java: 1.8.0_121
Android Studio: 3.0 Canary 4

And the project configurations:
android gradle plugin: 2.4.0-alpha7
gradle (using gradle wrapper): 3.4.1

Some of the above are almost bleeding edge versions. So I'm not surprised what you guys came across. But I don't have a clue what is the cause.

**Comment by Cutta** [comment] 2017-06-20 19:04
I solved it!!
I tried on Android Studio: 3.0 Canary 1 and its give me `Error:All flavors must now belong to a named flavor dimension. The flavor 'play' is not assigned to a flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html` and after some search I came across a solution from [stackoverflow](https://stackoverflow.com/a/44105240/3027225). 
on gradle add this line :
android{
...
flavorDimensions "versionCode"
}
It solved my problem. I can play around with code now :)

**Comment by gejiaheng** [comment] 2017-06-21 08:38
@Cutta 
Do you update the gradle plugin and gradle wrapper? And if you do, what versions do you update to?

**Comment by Cutta** [comment] 2017-06-21 08:53
No, I didn't update. My versions are:
classpath 'com.android.tools.build:gradle:3.0.0-alpha1'
As I said, I just add` flavorDimensions "versionCode"` this line on gradle under android{..}

**Comment by gejiaheng** [comment] 2017-06-21 09:03
@Cutta 
Ah, you've actually updated the android gradle plugin, the upstream version is 2.4.0-alpha7. I'll see what to do.

**Comment by Cutta** [comment] 2017-06-21 09:08
oh sorry. Yes I updated. Maybe I updated unconsciously :)

**Comment by gejiaheng** [comment] 2017-06-21 13:32
Hi, everyone, I've updated the gradle wrapper and gradle plugin to the bleeding edge versions in https://github.com/gejiaheng/Protein/pull/10. Check it out. And if you're still having problems, see **Attentions** in README.

**Comment by gejiaheng** [comment] 2017-06-22 15:19
@Cutta 
Would you please update to the latest codebase and test whether the build issue is resolved on your machine? Thanks!

**Comment by Cutta** [comment] 2017-06-23 06:39
@gejiaheng After updated the codebase project gives this error :( 
<img src = "https://i.hizliresim.com/r2ZVPm.png"/>

**Comment by gejiaheng** [comment] 2017-06-23 06:47
@Cutta 
Add android.enableAapt2=false to gradle.properties and try again.

**Comment by Cutta** [comment] 2017-06-23 07:07
@gejiaheng I'm sorry. There was no gradle.properties. I create and add this line but still gives same error.

**Comment by gejiaheng** [comment] 2017-09-15 01:00
Please reopen this issue again if anyone still has build problem.

**Closed as completed by gejiaheng** 2017-09-15 01:00 UTC
